/*!CK:1011468578!*//*1385952852,173209415*/

if (self.CavalryLogger) { CavalryLogger.start_js(["NP4uK"]); }

__d("ComposerXAttachment",["ComposerXStore","copyProperties"],function(a,b,c,d,e,f){var g=b('ComposerXStore'),h=b('copyProperties');function i(){"use strict";}i.prototype.getRoot=function(){"use strict";};i.prototype.initWithComponents=function(j){"use strict";};i.prototype.cleanup=function(){"use strict";};i.prototype.reset=function(){"use strict";};i.prototype.getComponent=function(j){"use strict";return g.get(this._composerID,j);};i.prototype.getComponentInstance=function(j){"use strict";var k=g.get(this._composerID,j);return k&&k.instance;};i.prototype.canSwitchAway=function(){"use strict";return true;};i.prototype.setComposerID=function(j){"use strict";this._composerID=j;};i.prototype.getComposerID=function(){"use strict";return this._composerID;};i.prototype.allowOGTagPreview=function(){"use strict";return false;};h(i.prototype,{attachmentClassName:''});e.exports=i;});
__d("Clock",["EventEmitter"],function(a,b,c,d,e,f){var g=b('EventEmitter'),h=new g();h.ANOMALY='anomaly';var i=30,j=Date.now(),k=[],l=0,m=1000;function n(){var p=Date.now()-j;return p<0||p>m*10;}function o(){var p=Date.now()-j;k[l]=p;l=(l+1)%i;if(n())h.emit(h.ANOMALY,p);j=Date.now();}h.getSamples=function(){return k.slice(l).concat(k.slice(0,l));};h.isAnomalous=n;setInterval(o,m,false);e.exports=h;});
__d("LogHistoryListeners",["Clock","ErrorUtils","LogHistory"],function(a,b,c,d,e,f){var g=b('Clock'),h=b('ErrorUtils'),i=b('LogHistory').getInstance('sys');g.addListener(g.ANOMALY,function(j){i.warn('clock_anomaly',g.getSamples());});h.addListener(function(j){i.error('error',JSON.stringify({guard:j.guard,line:j.line,message:j.message,script:j.script,stack:j.stack}));});});
__d("MarauderLogger",["Banzai","CacheStorage","MarauderConfig"],function(a,b,c,d,e,f){var g=b('Banzai'),h=b('CacheStorage'),i='client_event',j='navigation',k=180000,l='marauder',m='marauder_last_event_time',n='marauder_last_session_id',o={},p=[],q=false,r=null,s=null,t=null,u=0,v,w,x=false,y=new h('localstorage',''),z=b('MarauderConfig');function aa(){y.set(m,ba());}g.subscribe(g.SHUTDOWN,aa);function ba(){v=v||y.get(m)||0;return v;}function ca(){if(!x){w=y.get(n);x=true;}var qa=Date.now();if(!w||qa-k>ba()){w=qa.toString(16)+'-'+(~~(Math.random()*16777215)).toString(16);y.set(n,w);}return w;}function da(){return {user_agent:window.navigator.userAgent,screen_height:window.screen.availHeight,screen_width:window.screen.availWidth,density:(window.screen.devicePixelRatio||null),platform:(window.navigator.platform||null),locale:(window.navigator.language||null)};}function ea(){return {locale:navigator.language};}function fa(qa,ra,sa,ta,ua,va,wa){var xa=wa||Date.now();v=wa?Date.now():xa;ra=ra||r;return {name:qa,time:xa/1000,module:ra,obj_type:ta,obj_id:ua,uuid:va,extra:sa};}function ga(qa,ra,sa){return fa('content',null,{flags:ra},null,null,qa,sa);}function ha(qa){var ra=window.__mrdr;if(ra)for(var sa in ra){var ta=ra[sa];if(ta[3]!==0){delete ra[sa];if(sa==="1")if(t!==null){sa=t;}else continue;qa.push(ga(sa,1,ta[1]));qa.push(ga(sa,2,ta[2]));qa.push(ga(sa,3,ta[3]));}}}function ia(qa){ha(qa);if(qa.length===0)return;if(q)qa.push(fa('counters',null,o));var ra=g.BASIC,sa=z.gk_enabled;if(u===0&&sa){qa.push(fa('device_status',null,ea()));ra={delay:5000};}if(sa&&Math.random()<.01)qa.push(fa('device_info',null,da()));if(t!==null)for(var ta in qa){var ua=qa[ta];if(ua.uuid===null||typeof(ua.uuid)==='undefined')ua.uuid=t;}var va={app_ver:z.app_version,data:qa,log_type:i,seq:u++,session_id:ca()},wa=y.get('device_id');if(wa)va.device_id=wa;o={};q=false;g.post(l,va,ra);}function ja(qa){if(!o[qa])o[qa]=0;o[qa]++;q=true;}function ka(qa,ra,sa,ta,ua,va,wa){ia([fa(qa,ra,sa,ta,ua,va,wa)]);}function la(qa,ra){if(r!==ra){t=null;p.push(fa(j,r,{dest_module:ra,source_url:s,destination_url:qa}));r=ra;s=qa;}}function ma(qa,ra,sa){ka(ra?'show_module':'hide_module',qa,sa);}function na(qa){r=qa;}function oa(){return r;}function pa(qa){if(t===null){t=qa;if(qa!==null){ia(p);p=[];}}}e.exports={count:ja,log:ka,navigateTo:la,toggleModule:ma,setUUID:pa,setNavigationModule:na,getNavigationModule:oa};});
__d("EveryoneTestsLoggingConstants",[],function(a,b,c,d,e,f){e.exports={EVERYONE_TESTS_IMPRESSION:'everyone_tests_impression',EVERYONE_TESTS_CONVERSION:'everyone_tests_conversion'};});
__d("DeltaLoggingConstants",[],function(a,b,c,d,e,f){e.exports={DELTA_EVERYONE_IMPRESSION:'delta_everyone_impression',DELTA_EVERYONE_CONVERSION:'delta_everyone_conversion',DELTA_EVERYONE_OK_BUTTON_CLICKED:'delta_everyone_ok_button_clicked',DELTA_EVERYONE_CHANGE_BUTTON_CLICKED:'delta_everyone_change_button_clicked'};});